In [2]:
import pandas as pd

In [4]:
movies_csv = '../Resources/movies.csv.zip'
movies_df = pd.read_csv(movies_csv)
movies_df = movies_df[['Title', 'Year', 'IMDb','Netflix', 'Hulu', 'Prime Video', 'Disney+', 'Directors']]
movies_df

,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,Directors
0,Inception,2010,8.8,1,0,0,0,Christopher Nolan
1,The Matrix,1999,8.7,1,0,0,0,"Lana Wachowski,Lilly Wachowski"
2,Avengers: Infinity War,2018,8.5,1,0,0,0,"Anthony Russo,Joe Russo"
3,Back to the Future,1985,8.5,1,0,0,0,Robert Zemeckis
4,"The Good, the Bad and the Ugly",1966,8.8,1,0,1,0,Sergio Leone
...,...,...,...,...,...,...,...,...
16739,The Ghosts of Buxley Hall,1980,6.2,0,0,0,1,Bruce Bilson
16740,The Poof Point,2001,4.7,0,0,0,1,Neal Israel
16741,Sharks of Lost Island,2013,5.7,0,0,0,1,Neil Gelinas
16742,Man Among Cheetahs,2017,6.6,0,0,0,1,Richard Slater-Jones
16743,In Beaver Valley,1950,NaN,0,0,0,1,James Algar

In [34]:
clean_movies_df = movies_df.dropna(how='any').reset_index()
clean_movies_df

,index,Title,Year,IMDb,Netflix,Hulu,Prime Video,Disney+,Directors
0,0,Inception,2010,8.8,1,0,0,0,Christopher Nolan
1,1,The Matrix,1999,8.7,1,0,0,0,"Lana Wachowski,Lilly Wachowski"
2,2,Avengers: Infinity War,2018,8.5,1,0,0,0,"Anthony Russo,Joe Russo"
3,3,Back to the Future,1985,8.5,1,0,0,0,Robert Zemeckis
4,4,"The Good, the Bad and the Ugly",1966,8.8,1,0,1,0,Sergio Leone
...,...,...,...,...,...,...,...,...,...
15685,16738,Whispers: An Elephant's Tale,2000,5.0,0,0,0,1,Dereck Joubert
15686,16739,The Ghosts of Buxley Hall,1980,6.2,0,0,0,1,Bruce Bilson
15687,16740,The Poof Point,2001,4.7,0,0,0,1,Neal Israel
15688,16741,Sharks of Lost Island,2013,5.7,0,0,0,1,Neil Gelinas
15689,16742,Man Among Cheetahs,2017,6.6,0,0,0,1,Richard Slater-Jones

In [36]:
clean_movies_df.to_csv('clean_movies.csv', index=False, header=True)